basePath: /
definitions:
  model.CategoriesResponse:
    properties:
      categories:
        items:
          $ref: '#/definitions/model.CategoryResponse'
        type: array
      message:
        type: string
    type: object
  model.Category:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.CategoryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
      parent_id:
        type: integer
    type: object
  model.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  model.Product:
    properties:
      category:
        $ref: '#/definitions/model.Category'
      category_id:
        type: integer
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: number
      stocks:
        items:
          $ref: '#/definitions/model.Stock'
        type: array
      supplier:
        $ref: '#/definitions/model.Supplier'
      supplier_id:
        type: integer
      updated_at:
        type: string
    type: object
  model.Stock:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      id:
        type: integer
      location:
        type: string
      product:
        $ref: '#/definitions/model.Product'
      product_id:
        type: integer
      quantity:
        type: integer
      updated_at:
        type: string
    type: object
  model.StockResponse:
    properties:
      id:
        type: integer
      location:
        type: string
      product_name:
        type: string
      quantity:
        type: integer
    type: object
  model.StocksResponse:
    properties:
      message:
        type: string
      stocks:
        items:
          $ref: '#/definitions/model.StockResponse'
        type: array
    type: object
  model.SuccessResponse:
    properties:
      message:
        type: string
    type: object
  model.Supplier:
    properties:
      contact:
        type: string
      created_at:
        type: string
      deleted_at:
        type: string
      description:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  model.SupplierResponse:
    properties:
      contact:
        type: string
      description:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
    type: object
  model.SuppliersResponse:
    properties:
      message:
        type: string
      suppliers:
        items:
          $ref: '#/definitions/model.SupplierResponse'
        type: array
    type: object
host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a server for managing inventory.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Inventory API
  version: "1.0"
paths:
  /categories:
    get:
      description: Retrieve all categories or filter by query parameters
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.CategoriesResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get all categories
      tags:
      - categories
    post:
      consumes:
      - application/json
      description: Create a new category in the inventory
      parameters:
      - description: Category data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Create a new category
      tags:
      - categories
  /categories/{id}:
    delete:
      description: Soft deletes a category and reassigns its products to the default
        category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Soft delete a category
      tags:
      - categories
    put:
      consumes:
      - application/json
      description: Update a category by ID
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      - description: Category data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Category'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Update a category
      tags:
      - categories
  /categories/{id}/hard:
    delete:
      description: Hard deletes a category and reassigns its products to the default
        category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Hard delete a category
      tags:
      - categories
  /categories/{id}/recover:
    post:
      description: Recover a soft-deleted category by ID and reassign its products
        back to the category
      parameters:
      - description: Category ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Recover a deleted category
      tags:
      - categories
  /products:
    get:
      description: Retrieve all products or filter by ID, name, category ID, or supplier
        ID
      parameters:
      - description: Product ID
        in: query
        name: id
        type: integer
      - description: Product name
        in: query
        name: name
        type: string
      - description: Category ID
        in: query
        name: category_id
        type: integer
      - description: Supplier ID
        in: query
        name: supplier_id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
      summary: Get all products or filter by various criteria
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Add a new product to the inventory
      parameters:
      - description: Product to create
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Create a new product
      tags:
      - products
  /products/{id}:
    delete:
      description: Soft delete a product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Soft delete an existing product
      tags:
      - products
    put:
      consumes:
      - application/json
      description: Update details of an existing product
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      - description: Product to update
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/model.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Update an existing product
      tags:
      - products
  /products/{id}/recover:
    post:
      description: Recover a soft-deleted product by ID
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Recover a soft-deleted product
      tags:
      - products
  /products/hard/{id}:
    delete:
      description: Hard delete a product by ID along with its associated stocks
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Hard delete an existing product and its stocks
      tags:
      - products
  /stocks:
    get:
      description: Retrieve all stock items or filter by query parameters
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.StocksResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get all stock items
      tags:
      - stocks
    post:
      consumes:
      - application/json
      description: Create a new stock item in the inventory
      parameters:
      - description: Stock data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Stock'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Create a new stock item
      tags:
      - stocks
  /stocks/{id}:
    delete:
      description: Delete a stock item by ID
      parameters:
      - description: Stock ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Delete a stock item
      tags:
      - stocks
    put:
      consumes:
      - application/json
      description: Update a stock item by ID
      parameters:
      - description: Stock ID
        in: path
        name: id
        required: true
        type: integer
      - description: Stock data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Stock'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Update a stock item
      tags:
      - stocks
  /stocks/{id}/hard:
    delete:
      description: Permanently delete a stock item by ID
      parameters:
      - description: Stock ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Hard delete a stock item
      tags:
      - stocks
  /stocks/{id}/recover:
    post:
      description: Recover a soft-deleted stock item by ID
      parameters:
      - description: Stock ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Recover a deleted stock item
      tags:
      - stocks
  /suppliers:
    get:
      description: Retrieve all suppliers
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuppliersResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get all suppliers
      tags:
      - suppliers
    post:
      consumes:
      - application/json
      description: Create a new supplier in the inventory
      parameters:
      - description: Supplier data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Supplier'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Create a new supplier
      tags:
      - suppliers
  /suppliers/{id}:
    delete:
      description: Soft deletes a supplier by ID and sets the supplier field in related
        products to null
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Soft delete a supplier
      tags:
      - suppliers
    put:
      consumes:
      - application/json
      description: Update a supplier by ID
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      - description: Supplier data
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Supplier'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Update a supplier
      tags:
      - suppliers
  /suppliers/{id}/recover:
    post:
      description: Recover a soft-deleted supplier by ID and reassign its products
        back to the supplier
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Recover a deleted supplier
      tags:
      - suppliers
  /suppliers/hard/{id}:
    delete:
      description: Hard deletes a supplier by ID and sets the supplier field in related
        products to null
      parameters:
      - description: Supplier ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SuccessResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Hard delete a supplier
      tags:
      - suppliers
swagger: "2.0"
